//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.2.0
//     from Assets/Inputs/PlayerInputs.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputs : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputs()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputs"",
    ""maps"": [
        {
            ""name"": ""Fps"",
            ""id"": ""06fd11b0-325f-47a1-acf6-644f63873098"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""PassThrough"",
                    ""id"": ""6d45f46e-719b-40bb-bcc9-204faf6a756e"",
                    ""expectedControlType"": ""Dpad"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Run"",
                    ""type"": ""PassThrough"",
                    ""id"": ""8291a278-79c8-4c3c-b2cd-31ceb81f6384"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Crouch"",
                    ""type"": ""PassThrough"",
                    ""id"": ""ce3bedda-b03c-4d94-ab11-2981c055721a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""PassThrough"",
                    ""id"": ""cc46e05b-4d2e-4492-bc29-cdc0d5576a15"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""PassThrough"",
                    ""id"": ""7b546601-fb4d-4270-a13c-bd77e710660f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Shoot"",
                    ""type"": ""PassThrough"",
                    ""id"": ""a8e83c30-4130-4eb7-a6fd-8678d1d62f49"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MouseInput"",
                    ""type"": ""PassThrough"",
                    ""id"": ""0ea4edc2-5b96-4ea3-9b8c-eb9276ae4375"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interact_1"",
                    ""type"": ""PassThrough"",
                    ""id"": ""ea675a5d-61fa-4a4f-9b62-443c0166b1ce"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interact_2"",
                    ""type"": ""PassThrough"",
                    ""id"": ""f8d4a876-7817-49fa-ab70-5a1fb91b94aa"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Reload"",
                    ""type"": ""PassThrough"",
                    ""id"": ""49e4d34e-e602-4d1d-baee-3202d3b3675e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Aim"",
                    ""type"": ""PassThrough"",
                    ""id"": ""b0cbe1b7-25ac-4a69-872b-8d5a218412f1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ChangeView"",
                    ""type"": ""Button"",
                    ""id"": ""29ba53fa-dfaf-425a-a856-21315e195f19"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MousePosition"",
                    ""type"": ""Value"",
                    ""id"": ""0420ef1a-b90b-4d44-8c2a-6e0a3f09f7d1"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""bfb22952-20b3-4103-a3f4-797249794f7c"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""d59fc06a-f546-472a-9773-ff8d80952891"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""1250b2cb-d29f-467c-8990-a2cc6a244282"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""7d8f653c-53f3-43f8-8f58-6b2cd57e3ab7"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""b46ac444-8150-4ff9-b7d8-9c5db4ad5593"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""9e9866ee-617b-4056-aa03-c4c8683ce9c4"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3991baad-2ed7-41e6-b904-e3ccc8a52ec4"",
                    ""path"": ""<Keyboard>/leftCtrl"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Crouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""096f108d-d6fe-4949-ac97-80b587d97f55"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a7b2ff9b-d792-4e75-8b9b-9df3c222452f"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": ""Press(behavior=1)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""15e58bf7-dd42-4438-96fc-6d944e727210"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": ""Press(behavior=1)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2d44a285-0f5c-4ab6-87a3-75e67441c950"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""74580a0c-dbba-43f5-9dab-a9027b56b470"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseInput"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a66e6bcb-628e-41d7-b1d0-8bf421c2c2b9"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": ""Press(behavior=1)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact_1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a1a21c09-571a-4695-8ece-cfc0ea05fdf2"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": ""Press(behavior=1)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Reload"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""53c187b7-bbdf-4aef-ad38-c3398bd0e613"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f0c8eb83-030d-4ffd-8da7-7d6a68730440"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeView"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""34826ecf-32bd-4f17-b79b-a7874f62b9b5"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact_2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3c1aff11-a96a-4c61-bfc7-9cc7ecbe8e7c"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MousePosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Fps
        m_Fps = asset.FindActionMap("Fps", throwIfNotFound: true);
        m_Fps_Movement = m_Fps.FindAction("Movement", throwIfNotFound: true);
        m_Fps_Run = m_Fps.FindAction("Run", throwIfNotFound: true);
        m_Fps_Crouch = m_Fps.FindAction("Crouch", throwIfNotFound: true);
        m_Fps_Jump = m_Fps.FindAction("Jump", throwIfNotFound: true);
        m_Fps_Pause = m_Fps.FindAction("Pause", throwIfNotFound: true);
        m_Fps_Shoot = m_Fps.FindAction("Shoot", throwIfNotFound: true);
        m_Fps_MouseInput = m_Fps.FindAction("MouseInput", throwIfNotFound: true);
        m_Fps_Interact_1 = m_Fps.FindAction("Interact_1", throwIfNotFound: true);
        m_Fps_Interact_2 = m_Fps.FindAction("Interact_2", throwIfNotFound: true);
        m_Fps_Reload = m_Fps.FindAction("Reload", throwIfNotFound: true);
        m_Fps_Aim = m_Fps.FindAction("Aim", throwIfNotFound: true);
        m_Fps_ChangeView = m_Fps.FindAction("ChangeView", throwIfNotFound: true);
        m_Fps_MousePosition = m_Fps.FindAction("MousePosition", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Fps
    private readonly InputActionMap m_Fps;
    private IFpsActions m_FpsActionsCallbackInterface;
    private readonly InputAction m_Fps_Movement;
    private readonly InputAction m_Fps_Run;
    private readonly InputAction m_Fps_Crouch;
    private readonly InputAction m_Fps_Jump;
    private readonly InputAction m_Fps_Pause;
    private readonly InputAction m_Fps_Shoot;
    private readonly InputAction m_Fps_MouseInput;
    private readonly InputAction m_Fps_Interact_1;
    private readonly InputAction m_Fps_Interact_2;
    private readonly InputAction m_Fps_Reload;
    private readonly InputAction m_Fps_Aim;
    private readonly InputAction m_Fps_ChangeView;
    private readonly InputAction m_Fps_MousePosition;
    public struct FpsActions
    {
        private @PlayerInputs m_Wrapper;
        public FpsActions(@PlayerInputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_Fps_Movement;
        public InputAction @Run => m_Wrapper.m_Fps_Run;
        public InputAction @Crouch => m_Wrapper.m_Fps_Crouch;
        public InputAction @Jump => m_Wrapper.m_Fps_Jump;
        public InputAction @Pause => m_Wrapper.m_Fps_Pause;
        public InputAction @Shoot => m_Wrapper.m_Fps_Shoot;
        public InputAction @MouseInput => m_Wrapper.m_Fps_MouseInput;
        public InputAction @Interact_1 => m_Wrapper.m_Fps_Interact_1;
        public InputAction @Interact_2 => m_Wrapper.m_Fps_Interact_2;
        public InputAction @Reload => m_Wrapper.m_Fps_Reload;
        public InputAction @Aim => m_Wrapper.m_Fps_Aim;
        public InputAction @ChangeView => m_Wrapper.m_Fps_ChangeView;
        public InputAction @MousePosition => m_Wrapper.m_Fps_MousePosition;
        public InputActionMap Get() { return m_Wrapper.m_Fps; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(FpsActions set) { return set.Get(); }
        public void SetCallbacks(IFpsActions instance)
        {
            if (m_Wrapper.m_FpsActionsCallbackInterface != null)
            {
                @Movement.started -= m_Wrapper.m_FpsActionsCallbackInterface.OnMovement;
                @Movement.performed -= m_Wrapper.m_FpsActionsCallbackInterface.OnMovement;
                @Movement.canceled -= m_Wrapper.m_FpsActionsCallbackInterface.OnMovement;
                @Run.started -= m_Wrapper.m_FpsActionsCallbackInterface.OnRun;
                @Run.performed -= m_Wrapper.m_FpsActionsCallbackInterface.OnRun;
                @Run.canceled -= m_Wrapper.m_FpsActionsCallbackInterface.OnRun;
                @Crouch.started -= m_Wrapper.m_FpsActionsCallbackInterface.OnCrouch;
                @Crouch.performed -= m_Wrapper.m_FpsActionsCallbackInterface.OnCrouch;
                @Crouch.canceled -= m_Wrapper.m_FpsActionsCallbackInterface.OnCrouch;
                @Jump.started -= m_Wrapper.m_FpsActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_FpsActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_FpsActionsCallbackInterface.OnJump;
                @Pause.started -= m_Wrapper.m_FpsActionsCallbackInterface.OnPause;
                @Pause.performed -= m_Wrapper.m_FpsActionsCallbackInterface.OnPause;
                @Pause.canceled -= m_Wrapper.m_FpsActionsCallbackInterface.OnPause;
                @Shoot.started -= m_Wrapper.m_FpsActionsCallbackInterface.OnShoot;
                @Shoot.performed -= m_Wrapper.m_FpsActionsCallbackInterface.OnShoot;
                @Shoot.canceled -= m_Wrapper.m_FpsActionsCallbackInterface.OnShoot;
                @MouseInput.started -= m_Wrapper.m_FpsActionsCallbackInterface.OnMouseInput;
                @MouseInput.performed -= m_Wrapper.m_FpsActionsCallbackInterface.OnMouseInput;
                @MouseInput.canceled -= m_Wrapper.m_FpsActionsCallbackInterface.OnMouseInput;
                @Interact_1.started -= m_Wrapper.m_FpsActionsCallbackInterface.OnInteract_1;
                @Interact_1.performed -= m_Wrapper.m_FpsActionsCallbackInterface.OnInteract_1;
                @Interact_1.canceled -= m_Wrapper.m_FpsActionsCallbackInterface.OnInteract_1;
                @Interact_2.started -= m_Wrapper.m_FpsActionsCallbackInterface.OnInteract_2;
                @Interact_2.performed -= m_Wrapper.m_FpsActionsCallbackInterface.OnInteract_2;
                @Interact_2.canceled -= m_Wrapper.m_FpsActionsCallbackInterface.OnInteract_2;
                @Reload.started -= m_Wrapper.m_FpsActionsCallbackInterface.OnReload;
                @Reload.performed -= m_Wrapper.m_FpsActionsCallbackInterface.OnReload;
                @Reload.canceled -= m_Wrapper.m_FpsActionsCallbackInterface.OnReload;
                @Aim.started -= m_Wrapper.m_FpsActionsCallbackInterface.OnAim;
                @Aim.performed -= m_Wrapper.m_FpsActionsCallbackInterface.OnAim;
                @Aim.canceled -= m_Wrapper.m_FpsActionsCallbackInterface.OnAim;
                @ChangeView.started -= m_Wrapper.m_FpsActionsCallbackInterface.OnChangeView;
                @ChangeView.performed -= m_Wrapper.m_FpsActionsCallbackInterface.OnChangeView;
                @ChangeView.canceled -= m_Wrapper.m_FpsActionsCallbackInterface.OnChangeView;
                @MousePosition.started -= m_Wrapper.m_FpsActionsCallbackInterface.OnMousePosition;
                @MousePosition.performed -= m_Wrapper.m_FpsActionsCallbackInterface.OnMousePosition;
                @MousePosition.canceled -= m_Wrapper.m_FpsActionsCallbackInterface.OnMousePosition;
            }
            m_Wrapper.m_FpsActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Movement.started += instance.OnMovement;
                @Movement.performed += instance.OnMovement;
                @Movement.canceled += instance.OnMovement;
                @Run.started += instance.OnRun;
                @Run.performed += instance.OnRun;
                @Run.canceled += instance.OnRun;
                @Crouch.started += instance.OnCrouch;
                @Crouch.performed += instance.OnCrouch;
                @Crouch.canceled += instance.OnCrouch;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @Pause.started += instance.OnPause;
                @Pause.performed += instance.OnPause;
                @Pause.canceled += instance.OnPause;
                @Shoot.started += instance.OnShoot;
                @Shoot.performed += instance.OnShoot;
                @Shoot.canceled += instance.OnShoot;
                @MouseInput.started += instance.OnMouseInput;
                @MouseInput.performed += instance.OnMouseInput;
                @MouseInput.canceled += instance.OnMouseInput;
                @Interact_1.started += instance.OnInteract_1;
                @Interact_1.performed += instance.OnInteract_1;
                @Interact_1.canceled += instance.OnInteract_1;
                @Interact_2.started += instance.OnInteract_2;
                @Interact_2.performed += instance.OnInteract_2;
                @Interact_2.canceled += instance.OnInteract_2;
                @Reload.started += instance.OnReload;
                @Reload.performed += instance.OnReload;
                @Reload.canceled += instance.OnReload;
                @Aim.started += instance.OnAim;
                @Aim.performed += instance.OnAim;
                @Aim.canceled += instance.OnAim;
                @ChangeView.started += instance.OnChangeView;
                @ChangeView.performed += instance.OnChangeView;
                @ChangeView.canceled += instance.OnChangeView;
                @MousePosition.started += instance.OnMousePosition;
                @MousePosition.performed += instance.OnMousePosition;
                @MousePosition.canceled += instance.OnMousePosition;
            }
        }
    }
    public FpsActions @Fps => new FpsActions(this);
    public interface IFpsActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnRun(InputAction.CallbackContext context);
        void OnCrouch(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnPause(InputAction.CallbackContext context);
        void OnShoot(InputAction.CallbackContext context);
        void OnMouseInput(InputAction.CallbackContext context);
        void OnInteract_1(InputAction.CallbackContext context);
        void OnInteract_2(InputAction.CallbackContext context);
        void OnReload(InputAction.CallbackContext context);
        void OnAim(InputAction.CallbackContext context);
        void OnChangeView(InputAction.CallbackContext context);
        void OnMousePosition(InputAction.CallbackContext context);
    }
}
